version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

        # db mysql
    db:
        image: mysql:8.0
        restart: unless-stopped
        platform: linux/x86_64
        environment:
            MYSQL_DATABASE: dbdev-mhealth
            MYSQL_ROOT_PASSWORD: rootpassword 
            MYSQL_USER: laraveluser  
            MYSQL_PASSWORD: userpassword  # Password for the non-root user
        volumes:
                - ./mysql/dbdata:/var/lib/mysql
        ports:
            - "3308:3306" 
        networks:
            - laravel


    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
